Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Mireo.RepeatableFields': ['NodeTypes/*']
      inspector:
        dataTypes:
          repeatable:
            typeConverter: Mireo\RepeatableFields\TypeConverter\RepeatableConverter
            editor: Mireo.RepeatableFields/Inspector/Editors/RepeatableFieldEditor
          Mireo\RepeatableFields\Model\Repeatable:
            typeConverter: Mireo\RepeatableFields\TypeConverter\RepeatableToArrayConverter
        editors:
          Mireo.RepeatableFields/Inspector/Editors/RepeatableFieldEditor:
            editorOptions:
              buttonLabel: 'Neos.Neos:Main:content.inspector.editors.codeEditor.editCode'
              autoFocus: false
              disabled: false
              maxlength: null
              readonly: false
              buttonAddLabel: 'Add row'
              min: 0
              max: 100
              controls:
                move: true
                remove: true
                add: true
    Ui:
      resources:
        javascript:
          'Mireo.RepeatableFields:RepeatableField':
            resource: resource://Mireo.RepeatableFields/Public/Inspector/RepeatableFieldEditor/Plugin.js
